#ifndef _KEYCODES_H
#define _KEYCODES_H

#define KEYCODE_UNSET -1

#define KEYCODE_ARROW_UP    KEYCODE_UNSET
#define KEYCODE_ARROW_RIGHT KEYCODE_UNSET
#define KEYCODE_ARROW_DOWN  KEYCODE_UNSET
#define KEYCODE_ARROW_LEFT  KEYCODE_UNSET

#define KEYCODE_F1  KEYCODE_UNSET
#define KEYCODE_F2  KEYCODE_UNSET
#define KEYCODE_F3  KEYCODE_UNSET
#define KEYCODE_F4  KEYCODE_UNSET
#define KEYCODE_F5  KEYCODE_UNSET
#define KEYCODE_F6  KEYCODE_UNSET
#define KEYCODE_F7  KEYCODE_UNSET
#define KEYCODE_F8  KEYCODE_UNSET
#define KEYCODE_F9  KEYCODE_UNSET
#define KEYCODE_F10 KEYCODE_UNSET
#define KEYCODE_F11 KEYCODE_UNSET
#define KEYCODE_F12 KEYCODE_UNSET

#define KEYCODE_INSERT KEYCODE_UNSET
#define KEYCODE_HOME   KEYCODE_UNSET
#define KEYCODE_PGUP   KEYCODE_UNSET
#define KEYCODE_DEL    KEYCODE_UNSET
#define KEYCODE_END    KEYCODE_UNSET
#define KEYCODE_PGDN   KEYCODE_UNSET

#if defined(WIN32) || defined(_WIN32) || defined(__WIN32)

#undef KEYCODE_ARROW_UP
#undef KEYCODE_ARROW_RIGHT
#undef KEYCODE_ARROW_DOWN
#undef KEYCODE_ARROW_LEFT

#undef KEYCODE_F1
#undef KEYCODE_F2
#undef KEYCODE_F3
#undef KEYCODE_F4
#undef KEYCODE_F5
#undef KEYCODE_F6
#undef KEYCODE_F7
#undef KEYCODE_F8
#undef KEYCODE_F9
#undef KEYCODE_F10
#undef KEYCODE_F11
#undef KEYCODE_F12

#undef KEYCODE_INSERT
#undef KEYCODE_HOME
#undef KEYCODE_PGUP
#undef KEYCODE_DEL
#undef KEYCODE_END
#undef KEYCODE_PGDN

// ---------------------- //

#define KEYCODE_ARROW_UP    72
#define KEYCODE_ARROW_RIGHT 77
#define KEYCODE_ARROW_DOWN  80
#define KEYCODE_ARROW_LEFT  75

#define KEYCODE_F1   59
#define KEYCODE_F2   60
#define KEYCODE_F3   61
#define KEYCODE_F4   62
#define KEYCODE_F5   63
#define KEYCODE_F6   64
#define KEYCODE_F7   65
#define KEYCODE_F8   66
#define KEYCODE_F9   67
#define KEYCODE_F10  68
#define KEYCODE_F11 133
#define KEYCODE_F12 134

#define KEYCODE_INSERT 82
#define KEYCODE_HOME   71
#define KEYCODE_PGUP   73
#define KEYCODE_DEL    83
#define KEYCODE_END    79
#define KEYCODE_PGDN   81


#elif defined(__linux__)

#undef KEYCODE_ARROW_UP
#undef KEYCODE_ARROW_RIGHT
#undef KEYCODE_ARROW_DOWN
#undef KEYCODE_ARROW_LEFT

#define KEYCODE_ARROW_UP    65
#define KEYCODE_ARROW_RIGHT 67
#define KEYCODE_ARROW_DOWN  66
#define KEYCODE_ARROW_LEFT  68

#endif // os-check

#endif // _KEYCODES_H